window.__GI_LANG__={
back:'guicks',save:'Tallenna',cancel:'Peruuta',done:'Valmis',add:'Lisää',delete:'Poista',close:'Sulje',edit:'Muokkaa',search:'Haku',clear:'Tyhjennä',yes:'Kyllä',no:'Ei',ok:'OK',create:'Luo',copy:'Kopioi',share:'Jaa',today:'Tänään',all:'Kaikki',new:'Uusi',dismiss:'Sulje',set:'Aseta',accept:'Hyväksy',loading:'Ladataan…',error:'Virhe',noResults:'Ei tuloksia',optional:'valinnainen',confirm:'Vahvista',
homeTagline:'Nopeita työkaluja, ei hankaluuksia',homeSearch:'Etsi työkaluja…',
appNames:{qr:'QR-generaattori',currency:'Valuutta',favorites:'Suosikit',converter:'Muunnin',weather:'Sää',lucky:'Tuuri',calculator:'Laskin',stocks:'Osakkeet',translate:'Käännä',clock:'Kello',calendar:'Kalenteri',shopping:'Ostokset',reminders:'Muistutukset',notes:'Muistiinpanot',settings:'Asetukset'},
dockHint:'Pidä sovellusta painettuna vetääksesi dockiin',dockEditHint:'Napauta kuvaketta poistaaksesi · Napauta muualle lopettaaksesi',dockLongPress:'Pidä painettuna muokataksesi dockia',
settingsTitle:'⚙️ Asetukset',settingsAppearance:'Ulkoasu',settingsTheme:'Käyttöliittymäteema',settingsThemeDesc:'Käytössä kaikissa Guicks-sovelluksissa',settingsThemeLight:'☀️ Vaalea',settingsThemeDark:'🌙 Tumma',settingsThemeAuto:'🔄 Auto',settingsLang:'Kieli',settingsLangDesc:'Käyttöliittymän kieli',settingsData:'Tiedot',settingsSave:'Tallenna tiedot tiedostoon',settingsSaveDesc:'Vie .json-varmuuskopio',settingsLoad:'Lataa tiedot tiedostosta',settingsLoadDesc:'Palauta tallennettu varmuuskopio',settingsReset:'Nollaa',settingsClear:'Tyhjennä kaikki tiedot',settingsClearDesc:'Poista suosikit, telakka ja asetukset',settingsAbout:'Tietoa',settingsPrivacy:'Tietosuojakäytäntö',settingsVersion:'Versio',settingsDev:'Kehittäjä',settingsTools:'Asennetut työkalut',settingsApps:'{{n}} sovellusta saatavilla',settingsSaved:'✅ Varmuuskopio tallennettu!',settingsRestored:'✅ Palautettu! Ladataan…',settingsInvalidBackup:'❌ Virheellinen varmuuskopio',settingsDragged:'Vedä telakalle!',
confirmClearTitle:'Tyhjennetäänkö kaikki tiedot?',confirmClearMsg:'Tämä poistaa kaikki suosikit, kategoriat, telakan ja asetukset. Ei voi kumota.',confirmClearYes:'Kyllä, tyhjennä kaikki',confirmClearCancel:'Peruuta',
qrTitle:'QR-generaattori',qrSub:'URL · Yhteystieto · Sähköposti · WiFi · Teksti',qrGenerate:'Luo QR',qrCopied:'✅ Kopioitu!',qrPlaceholderUrl:'https://example.com',qrPlaceholderText:'Koodi, WiFi-salasana, osoite…',
currencyTitle:'Valuutta',currencySub:'Reaaliaikaiset vaihtokurssit',currencyFrom:'Mistä',currencyTo:'Mihin',currencySwap:'Vaihda',currencyUpdated:'Päivitetty',currencyError:'Kurssien lataus epäonnistui',
favTitle:'Suosikit',favSub:'Omat kirjanmerkkisi',favAddUrl:'Liitä URL — https://example.com',favSearch:'Etsi suosikeista…',favNewCat:'Uusi kategoria',favCatName:'esim. Reseptit, Työ, Perhe…',favCreate:'Luo kategoria',favEmpty:'Ei suosikkeja vielä
Liitä URL yllä',favDelConfirm:'Poistetaanko tämä suosikki?',
converterTitle:'Muunnin',converterSub:'Pituus · Paino · Lämpötila · Tilavuus',
weatherTitle:'Sää',weatherSub:'Reaaliaikainen sääennuste',weatherSearch:'Etsi kaupunkia — Helsinki, Tampere…',weatherSaved:'Tallennetut paikat',weatherFeels:'Tuntuu kuin',weatherHumidity:'Kosteus',weatherWind:'Tuuli',weatherPressure:'Ilmanpaine',weatherLocation:'Käytä sijaintiani',weatherToday:'Tänään',weatherHourly:'Tunneittain',weatherDaily:'7 päivää',
luckyTitle:'Tuuri',luckySub:'Noppa · Pyörä · Kolikko · Numero',luckyEntry:'Lisää nimi tai vaihtoehto…',luckyAdd:'Lisää',luckyClear:'Tyhjennä kaikki',luckyRoll:'Heitä',luckySpin:'Pyöritä',luckyFlip:'Heitä',luckyGen:'Luo',
calcTitle:'Laskin',calcSub:'Yksinkertainen · Tieteellinen · Edistynyt',calcSimple:'Yksinkertainen',calcSci:'Tieteellinen',calcAdv:'Edistynyt',calcEq:'Ratkaise yhtälö',calcCompute:'Laske',calcEqPh:'esim.  x^2 - 5*x + 6 = 0',
stocksTitle:'Osakkeet',stocksSub:'Reaaliaikaiset markkinatiedot',stocksSearch:'Etsi osakkeita — AAPL, Tesla, Microsoft…',stocksApiKey:'API-avain',stocksSaveKey:'Tallenna avain',stocksChange:'Muutos',stocksHigh:'Korkein',stocksLow:'Matalin',stocksVolume:'Volyymi',
translateTitle:'Käännä',translateSub:'100+ kieltä',translatePh:'Kirjoita tai liitä teksti tähän…',translateFrom:'Mistä',translateTo:'Mihin',translateSwap:'Vaihda',translateCopy:'Kopioi',translateSpeak:'Puhu',
clockTitle:'Kello',clockSub:'Maailmanaika · Hälytykset',clockTabClock:'🕐 Kello',clockTabWorld:'🌍 Maailma',clockTabAlarms:'⏰ Hälytykset',clockAdd:'Lisää',clockCityPh:'— Lisää kaupunki —',clockAlarmTime:'Aseta hälytysaika',clockAlarmLabel:'Etiketti (valinnainen)',clockAlarmSet:'Aseta',clockAlarmDismiss:'Sulje',clockAlarmNote:'⚠️ Hälytykset soivat vain tämän välilehden ollessa auki',clockNoCities:'Ei kaupunkeja — lisää yksi yllä',clockNoAlarms:'Ei hälytyksiä asetettu',
calTitle:'Kalenteri',calSub:'Kaikki tapahtumasi yhdessä paikassa',calYear:'Vuosi',calMonth:'Kuukausi',calWeek:'Viikko',calDay:'Päivä',calToday:'Tänään',calNewEvent:'Uusi tapahtuma',calEditEvent:'Muokkaa tapahtumaa',calEvTitle:'Otsikko',calEvDate:'Päivämäärä',calEvAllDay:'Koko päivä',calEvStart:'Alku',calEvEnd:'Loppu',calEvNotes:'Muistiinpanot',calEvCat:'Kategoria',calEvTitlePh:'Tapahtuman nimi…',calEvNotesPh:'Valinnaiset muistiinpanot…',calCatNamePh:'Kategorian nimi…',calNoEvents:'Ei tapahtumia tänä päivänä',calAddEvent:'+ Lisää tapahtuma',calCategories:'Kategoriat',calNewCat:'Uusi kategoria',
months:['Tammikuu','Helmikuu','Maaliskuu','Huhtikuu','Toukokuu','Kesäkuu','Heinäkuu','Elokuu','Syyskuu','Lokakuu','Marraskuu','Joulukuu'],monthsShort:['Tam','Hel','Maa','Huh','Tou','Kes','Hei','Elo','Syy','Lok','Mar','Jou'],days:['Su','Ma','Ti','Ke','To','Pe','La'],
shopTitle:'Ostoslista',shopSub:'Listasi on tyhjä',shopPh:'Lisää tuote…',shopClearDone:'Tyhjennä valmiit',shopDone:'valmiit',shopLeft:'jäljellä',shopEmpty:'Listasi on tyhjä
Lisää tuotteita yllä',
sections:{produce:'Hedelmät ja vihannekset',dairy:'Maitotuotteet',meat:'Liha',bakery:'Leipomo',frozen:'Pakasteet',drinks:'Juomat',snacks:'Naposteltavat',cleaning:'Siivoustarvikkeet',personal:'Hygieniatuotteet',pantry:'Ruokakomero',other:'Muut'},
remTitle:'Muistutukset',remSub:'Täällä ei ole vielä mitään',remPh:'Lisää muistutus…',remTagPh:'Uusi tunniste…',remClearDone:'Tyhjennä valmiit',remDone:'valmiit',remLeft:'jäljellä',remEmpty:'Ei muistutuksia vielä
Lisää yksi yllä',remNoTag:'Ei merkittyjä',remCreate:'+ Luo',remNewTagPh:'Tunnisteen nimi…',remTagExists:'Tunniste on jo olemassa',remEnterTag:'Syötä tunnisteen nimi',remTagInUse:'muistutukset käyttävät tätä tunnistetta',remCleared:'Tyhjennetty',remEmpty2:'Jo tyhjä',
notesTitle:'Muistiinpanot',notesSub:'Ei muistiinpanoja vielä',notesSearch:'Etsi muistiinpanoja…',notesTitlePh:'Otsikko…',notesBodyPh:'Aloita kirjoittaminen…',notesTagPh:'Tunnisteen nimi…',notesAddTag:'+ tunniste',notesMgTags:'# tunnisteet',notesNew:'Uusi muistiinpano',notesDelConfirm:'Poistetaanko tämä muistiinpano?',notesDeleted:'🗑 Muistiinpano poistettu',notesCopied:'📋 Kopioitu',notesEmpty:'Ei muistiinpanoja
Paina + luodaksesi',notesNoMatch:'Ei vastaavia muistiinpanoja',notesMgTitle:'Hallitse tunnisteita',notesTagExists:'Tunniste on jo olemassa',notesNoTags:'Ei tunnisteita vielä',notesTagInUse:'muistiinpanot käyttävät tätä tunnistetta',notesChars:'merk.',notesNoTag:'Ei tunnisteita',notesCopyFail:'Kopiointi ei saatavilla'
};