window.__GI_LANG__={
back:'guicks',
save:'Uložit',cancel:'Zrušit',done:'Hotovo',add:'Přidat',delete:'Smazat',close:'Zavřít',edit:'Upravit',search:'Hledat',clear:'Vymazat',yes:'Ano',no:'Ne',ok:'OK',create:'Vytvořit',copy:'Kopírovat',share:'Sdílet',today:'Dnes',all:'Vše',new:'Nový',dismiss:'Zavřít',set:'Nastavit',accept:'Přijmout',loading:'Načítání…',error:'Chyba',noResults:'Žádné výsledky',optional:'volitelné',confirm:'Potvrdit',
homeTagline:'Rychlé nástroje, žádné tření',homeSearch:'Hledat nástroje…',
appNames:{qr:'QR generátor',currency:'Měna',favorites:'Oblíbené',converter:'Převodník',weather:'Počasí',lucky:'Štěstí',calculator:'Kalkulačka',stocks:'Akcie',translate:'Překlad',clock:'Hodiny',calendar:'Kalendář',shopping:'Nákupy',reminders:'Připomínky',notes:'Poznámky',settings:'Nastavení'},
dockHint:'Podržte aplikaci pro přetažení do doku',dockEditHint:'Klepněte na ikonu pro odebrání · Klepněte jinam pro dokončení',dockLongPress:'Dlouze stiskněte pro úpravu doku',
settingsTitle:'⚙️ Nastavení',settingsAppearance:'Vzhled',settingsTheme:'Motiv rozhraní',settingsThemeDesc:'Platí pro všechny aplikace Guicks',settingsThemeLight:'☀️ Světlý',settingsThemeDark:'🌙 Tmavý',settingsThemeAuto:'🔄 Auto',settingsLang:'Jazyk',settingsLangDesc:'Jazyk rozhraní',settingsData:'Data',settingsSave:'Uložit data do souboru',settingsSaveDesc:'Exportovat zálohu .json',settingsLoad:'Načíst data ze souboru',settingsLoadDesc:'Obnovit uloženou zálohu',settingsReset:'Resetovat',settingsClear:'Vymazat všechna data',settingsClearDesc:'Odstranit oblíbené, dok a nastavení',settingsAbout:'O aplikaci',settingsPrivacy:'Zásady ochrany soukromí',settingsVersion:'Verze',settingsDev:'Vývojář',settingsTools:'Nainstalované nástroje',settingsApps:'{{n}} dostupných aplikací',settingsSaved:'✅ Záloha uložena!',settingsRestored:'✅ Obnoveno! Načítání…',settingsInvalidBackup:'❌ Neplatný záložní soubor',settingsDragged:'Přetáhněte do doku!',
confirmClearTitle:'Vymazat všechna data?',confirmClearMsg:'Tím se odstraní všechny oblíbené položky, kategorie, dok a nastavení. Nelze vrátit zpět.',confirmClearYes:'Ano, vymazat vše',confirmClearCancel:'Zrušit',
qrTitle:'QR generátor',qrSub:'URL · Kontakt · Email · WiFi · Text',qrGenerate:'Generovat QR',qrCopied:'✅ Zkopírováno!',qrPlaceholderUrl:'https://example.com',qrPlaceholderText:'Kód, heslo WiFi, adresa…',
currencyTitle:'Měna',currencySub:'Živé směnné kurzy',currencyFrom:'Z',currencyTo:'Na',currencySwap:'Vyměnit',currencyUpdated:'Aktualizováno',currencyError:'Kurzy se nepodařilo načíst',
favTitle:'Oblíbené',favSub:'Vaše osobní záložky',favAddUrl:'Vložte URL — https://example.com',favSearch:'Hledat v oblíbených…',favNewCat:'Nová kategorie',favCatName:'např. Recepty, Práce, Rodina…',favCreate:'Vytvořit kategorii',favEmpty:'Zatím žádné oblíbené
Vložte URL výše',favDelConfirm:'Odstranit tuto oblíbenou položku?',
converterTitle:'Převodník',converterSub:'Délka · Hmotnost · Teplota · Objem',
weatherTitle:'Počasí',weatherSub:'Předpověď v reálném čase',weatherSearch:'Hledat město — Praha, Brno…',weatherSaved:'Uložená místa',weatherFeels:'Pocitová teplota',weatherHumidity:'Vlhkost',weatherWind:'Vítr',weatherPressure:'Tlak',weatherLocation:'Použít mou polohu',weatherToday:'Dnes',weatherHourly:'Po hodinách',weatherDaily:'7 dní',
luckyTitle:'Štěstí',luckySub:'Kostka · Kolo · Mince · Číslo',luckyEntry:'Přidat jméno nebo možnost…',luckyAdd:'Přidat',luckyClear:'Vymazat vše',luckyRoll:'Hodit',luckySpin:'Otočit',luckyFlip:'Hodit',luckyGen:'Generovat',
calcTitle:'Kalkulačka',calcSub:'Jednoduchá · Vědecká · Pokročilá',calcSimple:'Jednoduchá',calcSci:'Vědecká',calcAdv:'Pokročilá',calcEq:'Vyřešit rovnici',calcCompute:'Vypočítat',calcEqPh:'např.  x^2 - 5*x + 6 = 0',
stocksTitle:'Akcie',stocksSub:'Tržní data v reálném čase',stocksSearch:'Hledat — AAPL, Tesla, Microsoft…',stocksApiKey:'API klíč',stocksSaveKey:'Uložit klíč',stocksChange:'Změna',stocksHigh:'Max',stocksLow:'Min',stocksVolume:'Objem',
translateTitle:'Překlad',translateSub:'100+ jazyků',translatePh:'Zadejte nebo vložte text zde…',translateFrom:'Z',translateTo:'Na',translateSwap:'Vyměnit',translateCopy:'Kopírovat',translateSpeak:'Mluvit',
clockTitle:'Hodiny',clockSub:'Světový čas · Budíky',clockTabClock:'🕐 Hodiny',clockTabWorld:'🌍 Svět',clockTabAlarms:'⏰ Budíky',clockAdd:'Přidat',clockCityPh:'— Přidat město —',clockAlarmTime:'Nastavit čas budíku',clockAlarmLabel:'Popisek (volitelné)',clockAlarmSet:'Nastavit',clockAlarmDismiss:'Zavřít',clockAlarmNote:'⚠️ Budíky zvoní jen když je tato záložka otevřena',clockNoCities:'Žádná města — přidejte výše',clockNoAlarms:'Žádné budíky nastaveny',
calTitle:'Kalendář',calSub:'Všechny vaše události na jednom místě',calYear:'Rok',calMonth:'Měsíc',calWeek:'Týden',calDay:'Den',calToday:'Dnes',calNewEvent:'Nová událost',calEditEvent:'Upravit událost',calEvTitle:'Název',calEvDate:'Datum',calEvAllDay:'Celý den',calEvStart:'Začátek',calEvEnd:'Konec',calEvNotes:'Poznámky',calEvCat:'Kategorie',calEvTitlePh:'Název události…',calEvNotesPh:'Volitelné poznámky…',calCatNamePh:'Název kategorie…',calNoEvents:'Žádné události tento den',calAddEvent:'+ Přidat událost',calCategories:'Kategorie',calNewCat:'Nová kategorie',
months:['Leden','Únor','Březen','Duben','Květen','Červen','Červenec','Srpen','Září','Říjen','Listopad','Prosinec'],monthsShort:['Led','Úno','Bře','Dub','Kvě','Čer','Čvc','Srp','Zář','Říj','Lis','Pro'],days:['Ne','Po','Út','St','Čt','Pá','So'],
shopTitle:'Nákupní seznam',shopSub:'Váš seznam je prázdný',shopPh:'Přidat položku…',shopClearDone:'Smazat dokončené',shopDone:'hotovo',shopLeft:'zbývá',shopEmpty:'Váš seznam je prázdný
Přidejte položky výše',
sections:{produce:'Ovoce a zelenina',dairy:'Mléčné výrobky',meat:'Maso',bakery:'Pekárna',frozen:'Mražené',drinks:'Nápoje',snacks:'Svačiny',cleaning:'Čistící prostředky',personal:'Hygiena',pantry:'Spíž',other:'Ostatní'},
remTitle:'Připomínky',remSub:'Zatím nic',remPh:'Přidat připomínku…',remTagPh:'Nový štítek…',remClearDone:'Smazat dokončené',remDone:'hotovo',remLeft:'zbývá',remEmpty:'Žádné připomínky
Přidejte jednu výše',remNoTag:'Nic není označeno',remCreate:'+ Vytvořit',remNewTagPh:'Název štítku…',remTagExists:'Štítek již existuje',remEnterTag:'Zadejte název štítku',remTagInUse:'připomínky používají tento štítek',remCleared:'Vymazáno',remEmpty2:'Již prázdné',
notesTitle:'Poznámky',notesSub:'Zatím žádné poznámky',notesSearch:'Hledat poznámky…',notesTitlePh:'Název…',notesBodyPh:'Začněte psát…',notesTagPh:'Název štítku…',notesAddTag:'+ štítek',notesMgTags:'# štítky',notesNew:'Nová poznámka',notesDelConfirm:'Smazat tuto poznámku?',notesDeleted:'🗑 Poznámka smazána',notesCopied:'📋 Zkopírováno',notesEmpty:'Žádné poznámky
Klepněte + pro vytvoření',notesNoMatch:'Žádné odpovídající poznámky',notesMgTitle:'Spravovat štítky',notesTagExists:'Štítek již existuje',notesNoTags:'Zatím žádné štítky',notesTagInUse:'poznámky používají tento štítek',notesChars:'znaků',notesNoTag:'Bez štítku',notesCopyFail:'Kopírování není dostupné'
};
